version: '3'

services:
  postgres:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_PASSWORD: secret
    volumes:
      - postgresdata:/var/lib/postgresql/data

  bot:
    image: mirabbos021/test-image:latest
    ports:
      - 8080:8080

volumes:
  postgresdata: